import { getAllProducers } from "@/lib/actions";
import styles from "./style.module.css";
import { sendInquiryAction } from "@/lib/actions";

export const dynamic = "force-dynamic";

export default async function InquiryPage({
  searchParams,
  }: {
    searchParams: Promise<{ companyId?: string; success?: string }>;
    }) {
      const params = await searchParams;
      const companyId = Number(params?.companyId ?? 0);
      const success = params?.success === "1";

      const companies = await getAllProducers();

      return (
      <div className={styles.page}>
      <div className={styles.container}>
      <h1 className={styles.title}>Zapytanie ofertowe</h1>

      {success && (
      <div className={styles.successBox}>
        Zapytanie zostało wysłane pomyślnie.
      </div>
      )}

                                                                                        <form action={sendInquiryAction} className={styles.form}>
                                                                                                  <div className={styles.field}>
                                                                                                              <label htmlFor="companyId">Firma</label>
                                                                                                                          <select
                                                                                                                                        id="companyId"
                                                                                                                                                      name="companyId"
                                                                                                                                                                    defaultValue={companyId || ""}
                                                                                                                                                                                  className={styles.select}
                                                                                                                                                                                                required
                                                                                                                                                                                                            >
                                                                                                                                                                                                                          <option value="">Wybierz firmę</option>
                                                                                                                                                                                                                                        {companies.map((company: any) => (
                                                                                                                                                                                                                                                        <option key={company.id} value={company.id}>
                                                                                                                                                                                                                                                                          {company.nazwa}
                                                                                                                                                                                                                                                                                          </option>
                                                                                                                                                                                                                                                                                                        ))}
                                                                                                                                                                                                                                                                                                                    </select>
                                                                                                                                                                                                                                                                                                                              </div>

                                                                                                                                                                                                                                                                                                                                        <div className={styles.field}>
                                                                                                                                                                                                                                                                                                                                                    <label htmlFor="customerName">Imię i nazwisko</label>
                                                                                                                                                                                                                                                                                                                                                                <input id="customerName" name="customerName" className={styles.input} required />
                                                                                                                                                                                                                                                                                                                                                                          </div>

                                                                                                                                                                                                                                                                                                                                                                                    <div className={styles.field}>
                                                                                                                                                                                                                                                                                                                                                                                                <label htmlFor="customerCompany">Firma</label>
                                                                                                                                                                                                                                                                                                                                                                                                            <input id="customerCompany" name="customerCompany" className={styles.input} />
                                                                                                                                                                                                                                                                                                                                                                                                                      </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                <div className={styles.field}>
                                                                                                                                                                                                                                                                                                                                                                                                                                            <label htmlFor="customerEmail">Email</label>
                                                                                                                                                                                                                                                                                                                                                                                                                                                        <input id="customerEmail" name="customerEmail" type="email" className={styles.input} required />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <div className={styles.field}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <label htmlFor="customerPhone">Telefon</label>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <input id="customerPhone" name="customerPhone" className={styles.input} />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <div className={styles.field}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <label htmlFor="serviceType">Typ usługi</label>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <select id="serviceType" name="serviceType" className={styles.select} required>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <option value="">Wybierz usługę</option>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <option value="Montaż SMT">Montaż SMT</option>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <option value="Montaż THT">Montaż THT</option>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <option value="Produkcja PCB">Produkcja PCB</option>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <option value="Montaż elektroniki">Montaż elektroniki</option>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <option value="Kontraktowy montaż elektroniki">Kontraktowy montaż elektroniki</option>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <option value="Inne">Inne</option>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </select>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <div className={styles.field}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <label htmlFor="quantity">Ilość / skala</label>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <input id="quantity" name="quantity" className={styles.input} placeholder="np. 1000 szt." />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <div className={styles.field}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <label htmlFor="deadline">Termin realizacji</label>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <input id="deadline" name="deadline" className={styles.input} placeholder="np. 4 tygodnie" />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <div className={styles.field}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <label htmlFor="message">Opis projektu</label>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <textarea id="message" name="message" className={styles.textarea} required />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <div className={styles.actions}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <button type="submit" className={styles.submitBtn}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                Wyślij zapytanie
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </form>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }